package com.pcstore.model.enums;

public enum Category {
    CPU, GPU, MOTHERBOARD, RAM, PSU, CASE,
    COOLING, COOLING_CPU_AIR, COOLING_CPU_LIQUID, COOLING_FAN,
    STORAGE_NVME, STORAGE_SATA, STORAGE_HDD,
    MONITOR,
    KEYBOARD, MOUSE, MOUSE_PAD, HEADPHONE, HEADSET,
    CONTROLLER, GAMEPAD, DRIVING_WHEEL,
    GAMING_CHAIR, SPEAKER, MICROPHONE, WEBCAM,
    THERMAL_PASTE, CABLE_MANAGEMENT, MONITOR_ARM,
    USB_HUB, CAPTURE_CARD, DESK_MAT,
    UPS,
    PREBUILT, ACCESSORY
}